spring:
    profiles:
        active: dev
---
spring:
    profiles: dev
    datasource:
        url: jdbc:mysql://localhost/user_register_sc?characterEncoding=UTF-8
        username: user_register_sc
        password: user_register_sc
        driverClassName: com.mysql.jdbc.Driver
    jpa:
        hibernate:
            ddl-auto: update
    thymeleaf.cache: false
    security.basic.enabled: false